import { useEffect, useMemo, useState } from "react";
import StatCard from "../components/dashboard/StatCard";
import AlertPanel from "../components/dashboard/AlertPanel";
import AnalyticsChart from "../components/dashboard/AnalyticsChart";
import AttackVisualization from "../components/dashboard/AttackVisualization";
import { getAlerts } from "../services/api";

export default function DashboardPage() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [apiError, setApiError] = useState("");

  useEffect(() => {
    let mounted = true;

    async function loadAlerts() {
      try {
        const data = await getAlerts();

        if (!mounted) {
          return;
        }

        setAlerts(Array.isArray(data) ? data : []);
        setApiError("");
      } catch {
        if (!mounted) {
          return;
        }

        setApiError("Security API unavailable.");
      } finally {
        if (mounted) {
          setLoading(false);
        }
      }
    }

    loadAlerts();

    const timer = setInterval(loadAlerts, 10000);

    return () => {
      mounted = false;
      clearInterval(timer);
    };
  }, []);

  const criticalCount = useMemo(
    () =>
      alerts.filter(
        (alert) => alert.severity?.toLowerCase() === "critical"
      ).length,
    [alerts]
  );

  const stats = [
    {
      label: "Alerts Received",
      value: String(alerts.length),
      trend: "Current API state",
    },
    {
      label: "Critical Alerts",
      value: String(criticalCount),
      trend: "Current API state",
    },
    {
      label: "Open Alerts",
      value: String(
        alerts.filter(
          (alert) => (alert.status || "open").toLowerCase() === "open"
        ).length
      ),
      trend: "Current API state",
    },
    {
      label: "Telemetry Status",
      value: apiError ? "Offline" : loading ? "Loading" : "Connected",
      trend: "FastAPI backend",
    },
  ];

  const chartData = [
    {
      name: "Current",
      alerts: alerts.length,
    },
  ];

  const displayAlerts = alerts.slice(0, 12).map((alert) => ({
    id: alert.alert_id,
    title: alert.title,
    source: alert.source_ip || alert.host || "unknown",
    target: alert.host || "endpoint",
    severity: alert.severity || "info",
    time: alert.created_at
      ? new Date(alert.created_at).toLocaleTimeString()
      : "unknown",
  }));

  return (
    <div>
      <header className="mb-6 rounded-2xl border border-cyan-400/25 bg-slate-900/50 p-5 shadow-[0_0_40px_rgba(0,213,255,0.12)] backdrop-blur-md">
        <p className="text-xs uppercase tracking-[0.2em] text-cyan-300">
          Security Operations Center
        </p>

        <h1 className="mt-2 text-2xl font-semibold sm:text-3xl">
          Cyber-Threat-Monitor
        </h1>

        <p className="mt-2 max-w-3xl text-sm text-slate-300">
          Monitor security events and detection alerts from the Cyber-Threat-Monitor
          backend.
        </p>
      </header>

      {apiError && (
        <div className="mb-6 rounded-xl border border-amber-400/30 bg-amber-950/20 p-4 text-sm text-amber-200">
          {apiError} Dashboard metrics are unavailable until the backend is
          reachable.
        </div>
      )}

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        {stats.map((item) => (
          <StatCard key={item.label} {...item} />
        ))}
      </div>

      <div className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-3">
        <div className="xl:col-span-2">
          <AnalyticsChart data={chartData} />
        </div>

        <AlertPanel alerts={displayAlerts} />
      </div>

      <div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-2">
        <section className="glass-panel rounded-2xl p-5">
          <h2 className="text-lg font-medium text-cyan-200">
            Detection Status
          </h2>

          <p className="mt-2 text-sm text-slate-300">
            Dashboard values are derived from alerts returned by the FastAPI
            backend. No synthetic security events are generated by the
            frontend.
          </p>

          <div className="mt-4 grid grid-cols-2 gap-3 text-sm">
            <div className="rounded-xl border border-cyan-400/20 bg-slate-950/50 p-3">
              <p className="text-slate-400">Critical alerts</p>
              <p className="mt-1 text-xl font-semibold text-red-300">
                {criticalCount}
              </p>
            </div>

            <div className="rounded-xl border border-cyan-400/20 bg-slate-950/50 p-3">
              <p className="text-slate-400">API status</p>
              <p className="mt-1 text-xl font-semibold text-cyan-300">
                {apiError ? "Offline" : loading ? "Loading" : "Connected"}
              </p>
            </div>
          </div>
        </section>

        <AttackVisualization />

        <section className="glass-panel rounded-2xl p-5">
          <h2 className="text-lg font-medium text-cyan-200">
            Threat Intelligence
          </h2>

          <p className="mt-2 text-sm text-slate-300">
            Threat-intelligence feeds are not connected in the current
            milestone.
          </p>

          <div className="mt-3 rounded-xl border border-cyan-400/20 bg-slate-950/50 p-3 text-xs text-slate-400">
            No external IOC, CVE, or threat-actor data is presented as live
            intelligence in v0.5.0.
          </div>
        </section>

        <section className="glass-panel rounded-2xl p-5 md:col-span-2">
          <h2 className="text-lg font-medium text-cyan-200">
            Realtime Activity Feed
          </h2>

          {loading ? (
            <p className="mt-3 text-sm text-slate-400">
              Loading alerts from the security API...
            </p>
          ) : displayAlerts.length === 0 ? (
            <p className="mt-3 text-sm text-slate-400">
              No security alerts have been received yet.
            </p>
          ) : (
            <ul className="mt-3 space-y-2 text-sm">
              {displayAlerts.slice(0, 4).map((alert) => (
                <li
                  key={alert.id}
                  className="rounded-xl border border-cyan-400/20 bg-slate-950/50 p-3"
                >
                  <p className="font-medium text-slate-100">{alert.title}</p>

                  <p className="mt-1 text-xs text-slate-400">
                    {alert.source} {"->"} {alert.target} | {alert.time}
                  </p>
                </li>
              ))}
            </ul>
          )}
        </section>
      </div>
    </div>
  );
}
